"""add strands and chekhovs

Revision ID: 2bc97d4a28bf
Revises: 3dbebde87c55
Create Date: 2026-08-11 23:12:42.864021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bc97d4a28bf'
down_revision: Union[str, None] = '3dbebde87c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chekhovs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planted_chapter_id', sa.String(length=36), nullable=True),
    sa.Column('payoff_chapter_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['payoff_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planted_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('outline_nodes', sa.Column('strands', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outline_nodes', 'strands')
    op.drop_table('chekhovs')
    # ### end Alembic commands ###
