"""add chapter commits

Revision ID: 3dbebde87c55
Revises: d4195185188e
Create Date: 2026-08-11 23:05:04.087643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dbebde87c55'
down_revision: Union[str, None] = 'd4195185188e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_events', sa.JSON(), nullable=False),
    sa.Column('state_deltas', sa.JSON(), nullable=False),
    sa.Column('entity_deltas', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('projection_status', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_commits')
    # ### end Alembic commands ###
