"""add composed path

Revision ID: 68ddb2067aba
Revises: 2bc97d4a28bf
Create Date: 2026-08-11 23:41:57.296299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68ddb2067aba'
down_revision: Union[str, None] = '2bc97d4a28bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_tasks', sa.Column('composed_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_tasks', 'composed_path')
    # ### end Alembic commands ###
